---
- name: Deploy user sshd config
  ansible.builtin.template:
    src: templates/00-user.conf.j2
    dest: /etc/ssh/sshd_config.d/00-user.conf
  when: ssh_public_key is defined
  register: ssh_config_deployed

- name: Restart sshd
  ansible.builtin.service:
    name: sshd
    state: restarted
  when: ssh_config_deployed is changed
